DATA:
  IMG_SIZE: 448
MODEL:
  TYPE: swin
  NAME: dora_tiny_448_start96_to64
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
  MTLORA:
    ENABLED: True
    ADAPTIVE: True
    R: [96, 96, 96, 96]
    SHARED_SCALE: [4.0]
    TASK_SCALE: [4.0]
    DROPOUT: [0.05, 0.05, 0.05, 0.05]
    TRAINABLE_SCALE_SHARED: False
    TRAINABLE_SCALE_PER_TASK: False
    INTERMEDIATE_SPECIALIZATION: False
    FREEZE_PRETRAINED: True
    SPLIT_QKV: False
    QKV_ENABLED: True
    PROJ_ENABLED: True
    FC1_ENABLED: True
    FC2_ENABLED: True
    DOWNSAMPLER_ENABLED: False
    ADAPTIVE_START_RANK: 96
    ADAPTIVE_END_AVG_RANK: 64
    ADAPTIVE_START_PRUNE_STEP_RATIO: 0.15
    ADAPTIVE_END_PRUNE_STEP_RATIO: 0.6
    ADAPTIVE_PRUNE_INTERVAL_STEP: 100
    ADAPTIVE_SENSITIVITY_BETA: 0.9
    ADAPTIVE_EPS: 1.0e-8
    REGULARIZATION_LOSS_ALPHA: 0.1
    R_PER_TASK:
      semseg: [96]
      normals: [96]
      sal: [96]
      human_parts: [96]
      edge: [96]
      depth: [96]
      shared: [96]
  DECODER_HEAD:
    semseg: hrnet
    normals: hrnet
    sal: hrnet
    human_parts: hrnet
    edge: hrnet
    depth: hrnet